sonar.projectKey=owasp-juice-shop
sonar.projectName=OWASP Juice Shop
sonar.projectVersion=20.1.1
sonar.sourceEncoding=UTF-8

sonar.sources=juice-shop
sonar.tests=juice-shop/test,juice-shop/frontend/src
sonar.test.inclusions=juice-shop/test/**/*.test.ts,juice-shop/frontend/src/**/*.spec.ts

sonar.exclusions=\
  juice-shop/test/**,\
  juice-shop/frontend/src/**/*.spec.ts,\
  juice-shop/**/node_modules/**,\
  juice-shop/**/dist/**,\
  juice-shop/**/build/**,\
  juice-shop/**/coverage/**,\
  juice-shop/frontend/.angular/**,\
  juice-shop/frontend/src/assets/**,\
  juice-shop/screenshots/**,\
  juice-shop/ftp/**,\
  juice-shop/uploads/**,\
  juice-shop/data/static/i18n/**,\
  juice-shop/data/static/codefixes/**,\
  juice-shop/data/static/web3-snippets/**,\
  juice-shop/*.md,\
  juice-shop/**/*.md,\
  juice-shop/**/*.png,\
  juice-shop/**/*.jpg,\
  juice-shop/**/*.jpeg,\
  juice-shop/**/*.gif,\
  juice-shop/**/*.svg,\
  juice-shop/**/*.stl,\
  juice-shop/**/*.zip,\
  juice-shop/**/*.kdbx,\
  juice-shop/**/*.pyc,\
  juice-shop/**/*.bak

sonar.coverage.exclusions=juice-shop/test/**,juice-shop/frontend/src/**/*.spec.ts
